// Game data: settings, fighter blueprints, stages, difficulty profiles.
// Ported from setting.py / heroes.py and tuned for the HTML5 build.
"use strict";

window.GAME_DATA = (() => {
  const settings = {
    width: 1480,
    height: 860,
    floorY: 684,
    gravity: 2180,
    moveSpeed: 480,
    guardSpeed: 190,
    airSpeed: 406,
    jumpSpeed: 872,
    dashSpeed: 1080,
    dashDuration: 0.14,
    roundTime: 76,
    roundsToWin: 2,
    arcadeMatches: 3,
    maxHealth: 220,
    maxMeter: 100,
    maxGuardHeat: 100,
    guardCoolRate: 30,
    lowHealthThreshold: 0.3,
    introTime: 1.35,
    roundFreezeTime: 1.5,
    matchIntroTime: 2.2,
    stageMargin: 72,
    fighterW: 116,
    fighterH: 176,
  };

  const C = {
    red: [242, 116, 73],
    gold: [250, 204, 90],
    cyan: [88, 208, 230],
    blue: [60, 113, 230],
    pink: [255, 93, 161],
    orange: [243, 166, 73],
    purple: [189, 106, 255],
    green: [116, 214, 146],
    white: [246, 241, 233],
  };

  const dirMap = (neutral, up, down, left, right) => ({ neutral, up, down, left, right });

  const fighters = [
    {
      key: "chen_ping_macro",
      scan: "月入¥2000,生活质量 > $3000",
      name: "陈平·购买力版",
      title: "Macro Card Zoner",
      accent: C.red, accent2: C.gold, coat: [79, 46, 36],
      basics: dirMap("陈平不等式", "眉山抛物线", "汇率压底", "美元回旋", "购买力直拳"),
      skills: dirMap("小院别墅雨", "宏观上冲", "黑板封线", "外逃缓冲", "大棋推进"),
      ult: "购买力总攻",
      taunt: "美国人民生活在水深火热之中!",
      victory: "陈平不等式,成立!",
      blurb: "用购买力话术远程压制。子弹多,耐心少。",
      range: 500, stageTheme: 1, aiStyle: "zone",
    },
    {
      key: "chen_ping_lecture",
      scan: "学历:研究经济问题的物理学家",
      name: "陈平·讲堂版",
      title: "Lecture Hall Control",
      accent: C.orange, accent2: [244, 228, 176], coat: [76, 64, 39],
      basics: dirMap("黑板公式", "讲台粉笔", "GDP地平线", "讲义翻页", "课堂点名"),
      skills: dirMap("眉山论剑", "函数升空", "数据砸盘", "课堂护盾", "台前冲锋"),
      ult: "折线图瀑布",
      taunt: "这个问题我三十年前就讲过了。",
      victory: "眉山论剑,胜负已分。",
      blurb: "地面控制 + 光束墙,节奏慢但读对就重击。",
      range: 400, stageTheme: 1, aiStyle: "control",
    },
    {
      key: "zhang_weiwei_civil",
      scan: "履历:走过一百多个国家",
      name: "张维为·文明版",
      title: "Civilizational Caster",
      accent: C.cyan, accent2: C.blue, coat: [25, 46, 72],
      basics: dirMap("文明型国家", "话语升空", "叙事压制", "比较镜像", "模式前推"),
      skills: dirMap("这就是中国", "国运天幕", "东方落点", "话语权护盾", "文明冲波"),
      ult: "东方升西方降",
      taunt: "我走过一百多个国家。",
      victory: "我觉得这就是一种自信。",
      reflectLine: "这就是一种自信",
      blurb: "话语波控场,中距离之王,稳到无聊就是最强。",
      range: 360, stageTheme: 0, aiStyle: "caster",
    },
    {
      key: "zhang_weiwei_studio",
      scan: "手机:国产 信号:满格自信",
      name: "张维为·演播室版",
      title: "Studio Tempo Controller",
      accent: [64, 154, 240], accent2: [167, 226, 255], coat: [32, 42, 86],
      basics: dirMap("比较优势", "演播灯塔", "圆桌卡点", "退一步再评", "连麦点题"),
      skills: dirMap("演播室聚光灯", "全场提问", "圆桌封路", "场外连线", "主持推进"),
      ult: "全场连麦",
      taunt: "中国人,你要自信!",
      victory: "可圈可点。",
      reflectLine: "这就是一种自信",
      blurb: "麦克风回旋镖 + 聚光灯,把每条路都变得别扭。",
      range: 430, stageTheme: 0, aiStyle: "studio",
    },
    {
      key: "lao_a_execute",
      scan: "报名表:FLEA 成人组",
      name: "牢A·海报版",
      title: "Poster Irony Trickster",
      accent: C.pink, accent2: [255, 220, 241], coat: [56, 24, 46],
      basics: dirMap("外协海报", "创业咖啡", "留学主题", "福华大厦", "成人组直冲"),
      skills: dirMap("FLEA报名表", "角落麦序", "海报糊脸", "文案回车", "留学生夜袭"),
      ult: "海报真身",
      taunt: "成人组在创业咖啡。",
      victory: "海报比对手更有主动权。",
      blurb: "活动海报变成弹幕,赢法是把擂台变成公告栏。",
      range: 350, stageTheme: 5, aiStyle: "trickster",
    },
    {
      key: "lao_a_budget",
      scan: "净资产:低于斩杀线",
      name: "牢A·斩杀线版",
      title: "Execution-Line Rushdown",
      accent: C.purple, accent2: C.gold, coat: [57, 33, 69],
      basics: dirMap("斩杀线", "飞袋上挑", "月末封底", "账单回旋", "处刑飞扑"),
      skills: dirMap("牢A降临", "Paycheck坠落", "生存压力", "处刑预告", "红温追击"),
      ult: "一线清屏",
      taunt: "你已经踩进斩杀线了。",
      victory: "月末了,账单来了。欢迎回家。",
      blurb: "贴脸压制,斩杀线既是机制也是情绪。",
      range: 260, stageTheme: 5, aiStyle: "rush",
    },
    {
      key: "fengge_dongbei",
      scan: "学历:建议凑个大专",
      name: "峰哥·东百版",
      title: "Rant Brawler",
      accent: [194, 116, 84], accent2: [245, 206, 120], coat: [85, 52, 34],
      basics: dirMap("东百锐评", "指点江山", "凑大专", "性压抑回身", "下沉重拳"),
      skills: dirMap("东百连喷", "高处俯冲", "地面锐评", "老铁回旋", "江山直推"),
      ult: "直播间开闸",
      taunt: "兄弟,你这是性压抑了。",
      victory: "恒河水,非常好喝!",
      blurb: "锐评型近战,角度刁钻,赢得越离谱越好笑。",
      range: 300, stageTheme: 4, aiStyle: "brawler",
    },
    {
      key: "hu_chenfeng_reviewer",
      scan: "手机:iPhone顶配 自评:爆赞",
      name: "户晨风·评测版",
      title: "Tech Review Skirmisher",
      accent: C.green, accent2: [170, 242, 197], coat: [34, 74, 58],
      basics: dirMap("苹果安卓相对论", "配置升空", "税单落地", "反向横评", "物流直送"),
      skills: dirMap("评测结论", "新机开箱", "价格腰斩", "返场复盘", "拍摄推进"),
      ult: "全平台对轰",
      taunt: "用什么手机?说。",
      victory: "祝你越来越苹果。",
      blurb: "评测节奏变成立回,对面一上头就是机会。",
      range: 390, stageTheme: 2, aiStyle: "reviewer",
    },
    {
      key: "hu_xijin_editor",
      scan: "持仓:A股 浮亏:复杂",
      name: "胡锡进·社评版",
      title: "Editorial Pressure",
      accent: [224, 94, 76], accent2: [246, 214, 156], coat: [76, 36, 38],
      basics: dirMap("老胡锐评", "连夜发文", "社评压底", "回旋余地", "指点江山"),
      skills: dirMap("环球社论", "热搜起飞", "A股日记", "口风微调", "话题推进"),
      ult: "老胡不装了",
      taunt: "事情是复杂的。",
      victory: "2800点以下,遍地是黄金!",
      reflectLine: "叼盘成功",
      blurb: "稳健施压,退路多,削血像热搜一样赖着不走。",
      range: 420, stageTheme: 3, aiStyle: "editor",
    },
  ];

  const stages = [
    {
      name: "这就是中国演播室",
      subtitle: "Studio lights, debate heat, and a live audience.",
      top: [10, 18, 36], bottom: [47, 20, 30], floor: [20, 23, 44],
      keywords: ["话语权", "文明型国家", "这就是中国", "东方升西方降"],
      prop: "studio",
    },
    {
      name: "眉山讲堂",
      subtitle: "Blackboard formulas and purchasing-power confidence.",
      top: [18, 25, 34], bottom: [43, 23, 20], floor: [24, 29, 45],
      keywords: ["陈平不等式", "购买力", "讲堂", "宏观判断"],
      prop: "blackboard",
    },
    {
      name: "评测区擂台",
      subtitle: "Phones, tax slips, and delivery-speed hot takes.",
      top: [13, 20, 31], bottom: [23, 17, 39], floor: [18, 23, 41],
      keywords: ["安卓", "苹果", "税单", "横评"],
      prop: "phones",
    },
    {
      name: "热搜评论场",
      subtitle: "The old-guard opinion machine never sleeps.",
      top: [18, 18, 30], bottom: [34, 18, 23], floor: [20, 21, 37],
      keywords: ["社评", "热搜", "A股", "老胡锐评"],
      prop: "ticker",
    },
    {
      name: "东百锐评间",
      subtitle: "Downward-looking glare, upward-reaching confidence.",
      top: [16, 16, 26], bottom: [43, 21, 20], floor: [22, 20, 34],
      keywords: ["指定没有你好果汁吃", "你太baby辣", "凑大专", "指点江山"],
      prop: "street",
    },
    {
      name: "牢A 处刑台",
      subtitle: "The line glows brighter when the monthly pressure hits.",
      top: [18, 12, 24], bottom: [50, 18, 33], floor: [25, 18, 34],
      keywords: ["斩杀线", "账单", "Paycheck", "处刑"],
      prop: "gallows",
    },
  ];

  const difficulties = [
    { name: "Casual", reaction: 0.34, aggression: 0.46, combo: 0.25, guard: 0.40, antiAir: 0.30 },
    { name: "Panelist", reaction: 0.24, aggression: 0.58, combo: 0.42, guard: 0.55, antiAir: 0.45 },
    { name: "War Room", reaction: 0.16, aggression: 0.72, combo: 0.62, guard: 0.72, antiAir: 0.64 },
  ];

  const ticker = [
    "方向键组合改变招式本体:W/A/S/D + J 或 K。",
    "本作为梗图恶搞:公众人物语录被做成了动画格斗套装。",
    "低血量回合会触发牢A斩杀线,部分角色能提前逼出来。",
    "AI 依赖延迟反应而不是读指令,难度会沿街机阶梯爬升。",
    "据传本场解说走过一百多个国家。",
    "场边记分牌:¥2000 > $3000,不接受反驳。",
    "斩杀线以下,一切都会加速。",
    "赛后采访只问一个问题:用什么手机?",
    "老胡观战表示:事情是复杂的,一方面……另一方面……",
  ];

  return { settings, fighters, stages, difficulties, ticker, C };
})();
